name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
author: "The Helm authors"
branding:
  color: anchor
  icon: check-circle
inputs:
  charts_dir:
    description: The charts directory
    default: charts
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
    required: true
runs:
  using: "node12"
  main: "main.js"
